export { Header } from './header';
export { Logo } from './logo';
export { Main } from './main';
export { Detail } from './detail';
export { Footer } from './footer';
export { Login } from './login';
export { AddProduct } from './addProduct';
export { Register } from './register';
export { Userlist } from './userlist';
export { Productlist } from './productlist';
export { Admin } from './admin';
export { SellerProduct } from './seller-product/index';
export { Profile } from './profile'
export { UserInfo } from './profile-form'
export { ChangePass } from './updatepass'